FROM ubuntu:focal

RUN apt-get update
RUN apt-get install -y curl
RUN curl -sL https://deb.nodesource.com/setup_20.x | bash -
RUN apt-get upgrade -y
RUN apt-get install -y nodejs

RUN apt-get install git dos2unix -y

WORKDIR /home/app

COPY main.sh main.sh
RUN dos2unix main.sh
COPY script.js script.js
COPY ca.pem ca.pem
COPY kafka.key kafka.key
COPY kafka.cert kafka.cert
COPY package*.json .

RUN npm install

RUN chmod +x main.sh
RUN chmod +x script.js

ENTRYPOINT [ "/home/app/main.sh" ]
